#!/bin/sh
#
init_partition_params() {
  BOOT_DEVICE="mmcblk0"
  DPS="p"

  BOOT_DEVICE="/dev/${BOOT_DEVICE}"
  BOOT_PARTITION="${BOOT_DEVICE}${DPS}1"
  IMAGE_PARTITION="${BOOT_DEVICE}${DPS}2"
  DATA_PARTITION="${BOOT_DEVICE}${DPS}3"
}

validate_imgfile_imgpart() {

  BOOT_CONFIG="cmdline.txt"
  
  log_begin_msg "Current squash image " $SQUASH_FILE && log_end_msg
  log_begin_msg "Current boot partition " $BOOT_PARTITION && log_end_msg
  log_begin_msg "Current image partition " $IMAGE_PARTITION && log_end_msg
  log_begin_msg "Current data partition " $DATA_PARTITION && log_end_msg
  log_begin_msg "Current boot device " $BOOT_DEVICE && log_end_msg
  log_begin_msg "Current boot config file " $BOOT_CONFIG && log_end_msg
}
