#!/bin/sh
#

validate_imgfile_imgpart() {
  log_msg "Squash image" $SQUASH_FILE
  log_msg "Boot partition" $BOOT_PARTITION
  log_msg "Image partition" $IMAGE_PARTITION
  log_msg "Data partition" $DATA_PARTITION
  
  BOOT_DEVICE=/dev/$(lsblk -no PKNAME "${BOOT_PARTITION}")
  log_msg "Boot device" $BOOT_DEVICE  
}
